// ============================================================
//  TEKSTY PORTALU UCZESTNIKA (/moje) i PANELU ADMINA — PL / EN
// ============================================================
window.PORTAL_CONTENT = {
  pl: {
    title: "Panel uczestnika",
    blocks: { 1: "Blok 1 · 9:30–10:30", 2: "Blok 2 · 10:45–11:45", 3: "Blok 3 · 12:00–13:00" },
    packages: { full: "Pełny pakiet (3 dni)", conference: "Tylko konferencja (7 maja)", conference_lunch: "Konferencja (7 maja) + obiad" },
    login: {
      title: "Zaloguj się do panelu uczestnika",
      lead: "Podaj e-mail użyty przy zapisie. Wyślemy Ci jednorazowy link — bez hasła.",
      email: "Twój e-mail", send: "Wyślij link", sending: "Wysyłanie…",
      sentTitle: "Sprawdź skrzynkę", sentLead: "Wysłaliśmy link do logowania na {{email}}. Link działa 1 godzinę. Nie widzisz maila? Zajrzyj do spamu.",
      notFound: "Nie znaleźliśmy zgłoszenia z tym adresem. Użyj e-maila podanego w formularzu zapisów albo napisz do nas: {{contact}}.",
      devOpen: "Tryb testowy: otwórz link logowania", devHint: "W trybie testowym e-maile nie są wysyłane. Konta testowe: {{emails}}",
      notRegistered: "Nie masz jeszcze zgłoszenia?", register: "Zapisz się na konferencję",
      unregisteredTitle: "Jesteś zalogowany, ale nie mamy Twojego zgłoszenia",
      unregisteredLead: "Adres {{email}} nie figuruje na liście uczestników. Jeśli zapisałeś się innym e-mailem, wyloguj się i użyj tamtego. Jeśli to pomyłka, napisz: {{contact}}.",
    },
    nav: { overview: "Mój udział", workshops: "Warsztaty", options: "Program dodatkowy", profile: "Dane i dieta", networking: "Uczestnicy", info: "Informacje praktyczne", logout: "Wyloguj" },
    overview: {
      hello: "Cześć, {{name}}!", lead: "Tu ustawisz wszystko, co dotyczy Twojego udziału w konferencji.",
      packageLabel: "Twój pakiet", statusLabel: "Płatność", paid: "opłacona", unpaid: "oczekuje na wpłatę",
      unpaidHint: "Miejsce potwierdzimy po zaksięgowaniu wpłaty. Dane do przelewu znajdziesz w Informacjach praktycznych.",
      workshopsLabel: "Warsztaty", workshopsPicked: "wybrane: {{n}} z 3", workshopsNone: "jeszcze nie wybrane", workshopsNA: "nie obejmuje Twojego pakietu",
      todo: "Do zrobienia",
      tasks: { pay: "Opłać udział", workshops: "Wybierz warsztaty (3 bloki)", options: "Potwierdź udział w programie dodatkowym", diet: "Sprawdź wymagania dietetyczne", networking: "Dołącz do listy uczestników" },
      deadline: "Wybór warsztatów możesz zmieniać do {{date}}.",
      calendar: "Dodaj do kalendarza", program: "Zobacz pełny program",
    },
    workshops: {
      title: "Warsztaty — sobota 8 maja", lead: "Wybierz jedną sesję w każdym bloku. Liczba miejsc jest ograniczona; wybór możesz zmieniać do {{date}}.",
      seatsLeft: "wolne miejsca: {{n}}", full: "brak miejsc", chosen: "Wybrano", choose: "Wybieram", change: "Zmień", remove: "Usuń wybór",
      notInPackage: "Warsztaty sobotnie są w pakiecie pełnym. Chcesz dołączyć? Napisz do nas: {{contact}}.",
      deadlinePassed: "Termin zmian minął. W sprawie zmian napisz do nas: {{contact}}.",
      errFull: "Ta sesja jest już pełna. Wybierz inną.", saved: "Zapisano.",
    },
    options: {
      title: "Program dodatkowy", lead: "Zaznacz, w czym weźmiesz udział — dzięki temu zaplanujemy catering i transport.",
      items: {
        school_visits: { label: "Czwartek · wizyty studyjne (Strumienie, Azymut)", hint: "dla chętnych, ograniczona liczba miejsc" },
        gocook: { label: "Czwartek 18:00 · warsztaty kulinarne i kolacja w GoCook", hint: "" },
        garden: { label: "Piątek 18:00 · Garden Party w Szkole Ziarno", hint: "" },
        mass: { label: "Sobota 8:00 · Msza św. w Szkole Ziarno", hint: "opcjonalnie" },
        tour: { label: "Sobota 15:00 · zwiedzanie Starego Miasta z przewodnikiem", hint: "" },
      },
      conferenceOnly: "Twój pakiet obejmuje piątkową konferencję. Program dodatkowy jest w pakiecie pełnym — chcesz go rozszerzyć? Napisz: {{contact}}.",
      save: "Zapisz", saved: "Zapisano.",
    },
    profile: {
      title: "Dane i dieta", lead: "Te dane widzą organizatorki. Na liście uczestników pokazujemy tylko to, na co się zgodzisz.",
      email: "E-mail", org: "Organizacja / szkoła", role: "Stanowisko", country: "Kraj", diet: "Wymagania dietetyczne", dietHint: "np. wegetariańska, bezglutenowa, alergie",
      networking: "Pokaż mnie na liście uczestników", networkingHint: "Imię, nazwisko, organizacja, stanowisko, kraj i e-mail — widoczne tylko dla zalogowanych uczestników.",
      lang: "Język komunikacji", save: "Zapisz", saved: "Zapisano.",
    },
    networking: {
      title: "Uczestnicy", lead: "Osoby, które zgodziły się na kontakt. Napisz przed konferencją, umów się na kawę w Warszawie.",
      count: "{{n}} osób na liście", noConsent: "Nie jesteś na liście. Włącz widoczność w zakładce „Dane i dieta”, żeby inni mogli Cię znaleźć.", search: "Szukaj po nazwisku, organizacji, kraju",
    },
    info: { title: "Informacje praktyczne", lead: "Lokalizacje, dojazd, noclegi i płatność są na stronie głównej.", open: "Otwórz informacje praktyczne", pay: "Instrukcja płatności", faq: "FAQ", contact: "Kontakt z biurem konferencji" },
    common: { back: "← Strona konferencji", loading: "Ładowanie…", error: "Coś poszło nie tak. Spróbuj ponownie.", yes: "tak", no: "nie" },
    admin: {
      title: "Panel organizatora", participants: "Uczestnicy", sessions: "Warsztaty", catering: "Catering i opcje", export: "Eksport CSV",
      filters: { all: "wszyscy", paid: "opłaceni", unpaid: "nieopłaceni", full: "pełny pakiet", conference: "tylko konferencja" },
      cols: { name: "Imię i nazwisko", email: "E-mail", org: "Organizacja", country: "Kraj", package: "Pakiet", paid: "Opłacone", picks: "Warsztaty", diet: "Dieta", options: "Opcje" },
      markPaid: "Oznacz opłacone", markUnpaid: "Cofnij", seats: "{{taken}} / {{cap}}", noPicks: "—",
      counts: { total: "Zgłoszeń", paid: "Opłaconych", full: "Pełny pakiet", diets: "Z dietą" },
      loginLead: "Panel dla organizatorek. Zaloguj się e-mailem z listy administratorów.",
    },
  },
  en: {
    title: "Participant portal",
    blocks: { 1: "Block 1 · 9:30–10:30", 2: "Block 2 · 10:45–11:45", 3: "Block 3 · 12:00–13:00" },
    packages: { full: "Full package (3 days)", conference: "Conference only (7 May)", conference_lunch: "Conference (7 May) + lunch" },
    login: {
      title: "Sign in to the participant portal",
      lead: "Enter the e-mail you used to register. We'll send you a one-time link — no password.",
      email: "Your e-mail", send: "Send link", sending: "Sending…",
      sentTitle: "Check your inbox", sentLead: "We've sent a sign-in link to {{email}}. It's valid for 1 hour. Can't see it? Check spam.",
      notFound: "We couldn't find a registration with this address. Use the e-mail from your registration form or write to us: {{contact}}.",
      devOpen: "Test mode: open the sign-in link", devHint: "In test mode no e-mails are sent. Test accounts: {{emails}}",
      notRegistered: "Not registered yet?", register: "Register for the conference",
      unregisteredTitle: "You're signed in, but we have no registration for you",
      unregisteredLead: "The address {{email}} is not on the participants list. If you registered with a different e-mail, sign out and use that one. If this is a mistake, write to {{contact}}.",
    },
    nav: { overview: "My participation", workshops: "Workshops", options: "Extra program", profile: "Details and diet", networking: "Participants", info: "Practical info", logout: "Sign out" },
    overview: {
      hello: "Hello, {{name}}!", lead: "Everything about your participation in one place.",
      packageLabel: "Your package", statusLabel: "Payment", paid: "paid", unpaid: "awaiting payment",
      unpaidHint: "Your seat is confirmed once the payment arrives. Bank details are in Practical info.",
      workshopsLabel: "Workshops", workshopsPicked: "chosen: {{n}} of 3", workshopsNone: "not chosen yet", workshopsNA: "not included in your package",
      todo: "To do",
      tasks: { pay: "Pay the fee", workshops: "Choose your workshops (3 blocks)", options: "Confirm the extra program", diet: "Check dietary requirements", networking: "Join the participants list" },
      deadline: "You can change your workshop choice until {{date}}.",
      calendar: "Add to calendar", program: "See the full program",
    },
    workshops: {
      title: "Workshops — Saturday 8 May", lead: "Choose one session in each block. Seats are limited; you can change your choice until {{date}}.",
      seatsLeft: "seats left: {{n}}", full: "full", chosen: "Chosen", choose: "Choose", change: "Change", remove: "Remove",
      notInPackage: "Saturday workshops are part of the full package. Want to join? Write to us: {{contact}}.",
      deadlinePassed: "The change deadline has passed. For changes write to us: {{contact}}.",
      errFull: "This session is full. Pick another one.", saved: "Saved.",
    },
    options: {
      title: "Extra program", lead: "Tick what you'll join — it helps us plan catering and transport.",
      items: {
        school_visits: { label: "Thursday · school visits (Strumienie, Azymut)", hint: "optional, limited places" },
        gocook: { label: "Thursday 18:00 · cooking workshop and dinner at GoCook", hint: "" },
        garden: { label: "Friday 18:00 · garden party at Ziarno School", hint: "" },
        mass: { label: "Saturday 8:00 · Holy Mass at Ziarno School", hint: "optional" },
        tour: { label: "Saturday 15:00 · guided tour of the Old Town", hint: "" },
      },
      conferenceOnly: "Your package covers the Friday conference. The extra program is part of the full package — want to upgrade? Write to: {{contact}}.",
      save: "Save", saved: "Saved.",
    },
    profile: {
      title: "Details and diet", lead: "The organisers see these details. On the participants list we show only what you agree to.",
      email: "E-mail", org: "Organisation / school", role: "Role", country: "Country", diet: "Dietary requirements", dietHint: "e.g. vegetarian, gluten-free, allergies",
      networking: "Show me on the participants list", networkingHint: "Name, organisation, role, country and e-mail — visible only to signed-in participants.",
      lang: "Communication language", save: "Save", saved: "Saved.",
    },
    networking: {
      title: "Participants", lead: "People who agreed to be contacted. Write before the conference, meet for coffee in Warsaw.",
      count: "{{n}} people on the list", noConsent: "You're not on the list. Enable visibility in “Details and diet” so others can find you.", search: "Search by name, organisation, country",
    },
    info: { title: "Practical info", lead: "Venues, travel, accommodation and payment are on the main site.", open: "Open practical info", pay: "Payment instructions", faq: "FAQ", contact: "Contact the conference office" },
    common: { back: "← Conference website", loading: "Loading…", error: "Something went wrong. Try again.", yes: "yes", no: "no" },
    admin: {
      title: "Organiser panel", participants: "Participants", sessions: "Workshops", catering: "Catering and options", export: "Export CSV",
      filters: { all: "all", paid: "paid", unpaid: "unpaid", full: "full package", conference: "conference only" },
      cols: { name: "Name", email: "E-mail", org: "Organisation", country: "Country", package: "Package", paid: "Paid", picks: "Workshops", diet: "Diet", options: "Options" },
      markPaid: "Mark paid", markUnpaid: "Undo", seats: "{{taken}} / {{cap}}", noPicks: "—",
      counts: { total: "Registrations", paid: "Paid", full: "Full package", diets: "With diet" },
      loginLead: "Panel for organisers. Sign in with an e-mail from the admin list.",
    },
  },
};
